project_id = "rzvkcsuluelkkcovvaqz"

[auth]
additional_redirect_urls = ["https://d15kwzkstetaby.cloudfront.net/**"]

[functions.search-flights]
verify_jwt = true

[functions.search-airports]
verify_jwt = true

[functions.confirm-flight-price]
verify_jwt = true

[functions.create-flight-order]
verify_jwt = true

[functions.refresh-ams-prices]
verify_jwt = false

[functions.refresh-ams-prices-3-4]
verify_jwt = false

[functions.refresh-ams-prices-5-6]
verify_jwt = false

[functions.refresh-ams-prices-7-8]
verify_jwt = false

[functions.refresh-ams-prices-9-10]
verify_jwt = false

[functions.refresh-ams-prices-11-12]
verify_jwt = false

[functions.refresh-ams-prices-13-14]
verify_jwt = false

[functions.refresh-ams-prices-15-16]
verify_jwt = false

[functions.refresh-ams-prices-17-18]
verify_jwt = false

[functions.refresh-ams-prices-19-20]
verify_jwt = false
